repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types: [python]
        files: mysq_dump_anonymizer/
        entry: poetry run mypy
        pass_filenames: true

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [python]
        files: mysq_dump_anonymizer/
        entry: poetry run pylint
        pass_filenames: true
